In [3]:
import numpy as np
x = np.array([n for n in range(6)])
print(x)

[0 1 2 3 4 5]


In [8]:
a = np.array([1,2])
print(a)
b=np.array([2,1])
print(b)

print(a+b)

[1 2]
[2 1]
[3 3]


In [9]:
a = [1,2]
b = [2,1]
print (a+b)

[1, 2, 2, 1]


In [15]:
a = np.array([1,2])
print(a)
b=np.array([2,1])
print(b)
print('a+b',a+b)
print('a-b',a-b)
print('2a+b',2*a+b)
print('a+2b',a+2*b)

[1 2]
[2 1]
a+b [3 3]
a-b [-1  1]
2a+b [4 5]
a+2b [5 4]


In [20]:
#내적... dot 연산자
b = np.array([1,3])
c = np.array([4,2])
#내적...b dot c = 1x4 +3x2 = 10
y = b.dot(c)
print(y)


10


In [23]:
#백터의 크기
d = np.array([6,6])
#백터의 크기...norm = sqrt(a_1**2+a_2**2+,,,)
print(np.linalg.norm(d))

a=np.array([1,3])
print(np.linalg.norm(a))

8.48528137423857
3.1622776601683795


In [38]:
#백터의 내적... 곱의합으로 표현
## 내적의 합으로 두벡터의 합을 구할 수 있다.
sum = 0
for i in range(1,11,1):
    sum+=i
print(sum)

#내적... 곱의 합
a = np.array([1 for x in range(10)])
print(a)
b = np.array([x+1 for x in range(10)])
print(b)
sum = a.dot(b)
print(sum)

a = np.ones(1000) #1을 계속 반환
b= np.arange(1,1000+1)
print(a)
print(b)

55
[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10]
55
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

In [56]:
a = np.array([1 for x in range(10)])
b = np.array([x+1 for x in range(10)])
c= int(input('단 입력 : '))
if c>0:
    b=c*b
    sum = a.dot(b)
    print('{}단의 총합 : {}'.format(c,sum))

단 입력 : 7
7단의 총합 : 385


## 미분

In [ ]:
f(x) = x **2 #x에 대한 식(1)
df(x) = 2x #.. 식(1)에 대해서 x에 대한 1차 미분

f(x) = x**2+w**2 #x에 대한 식(2)
dx_f(x,w) = 2x #..식 (2)에 대해서 x에 대한 1차 미분
dw_f(x.w)= 2w #.. 식(2)에 대해서 w에 대한 2차 미분

In [ ]:
def f(w0, w1):
    return w0**2 + 2*w0*w1 + 3  #x^2 + 2xy +3
def df_dw0(w0,w1):
    return 2*w0 +2w1 #2x +2y
def df_dw1(w0,w1):
    return 2*w0 #2x